### PR TITLE
Batch Mutations for creating, updating, and deleting #438

### PR DESCRIPTION
**Pull request by keithhackbarth**
Batch mutations for creating, updating, and deleting.

## Description

Batched mutations are mutations that mutate multiple objects at once.
Mutations with a filter function or accept a list of objects that return a list.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

#438 

## Checklist
- [x ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

## Key Considerations When Reviewing

Previously, batch creation in Strawberry Django was an undocumented and untested feature, relying on hidden logic to adjust argument typing. To support batch operations as an official feature (including updates and deletes), I updated the syntax approach, which introduces a breaking change.

The new method explicitly requires batch mutations to take a `list` type as an argument. This makes the behavior more straightforward, consistent, and explicit.

## Summary by Sourcery

Implement batch mutations for creating, updating, and deleting multiple objects simultaneously, requiring list-type arguments for clarity and consistency. Update documentation and add tests to support this new feature.

New Features:
- Introduce batch mutations for creating, updating, and deleting multiple objects at once, allowing operations to accept a list of objects and return a list.

Enhancements:
- Refactor mutation logic to explicitly require batch mutations to take a list type as an argument, improving clarity and consistency.

Documentation:
- Update documentation to include information on using batch mutations for create, update, and delete operations.

Tests:
- Add tests for batch mutations to ensure correct functionality for create, update, and delete operations with lists.

### CODE REVIEW

**Comment by keithhackbarth** [comment]
@bellini666, @thclark, @patrick91 - What is the process for requesting a PR review here?

**Comment by bellini666** [comment]
Hi @keithhackbarth ,

Sorry for taking long to review this. I'm in the middle of a relocation (just moved from Brazil to the Netherlands) and it is consuming all of my time.

I'll try to take some time during this week, or maximum next weekend to review this!

**Comment by keithhackbarth** [comment]
Thanks, @bellini666 – and congrats on the move! Hope you're settling in well and enjoying the Netherlands. 

Quick semi-related question: is there a specific reason we disable all DjangoOptimizerExtension for mutations? Just want to clarify the reasoning behind that approach. When I remove those lines in mutations/fields.py and rerun pytest - everything works and its more performant so trying to figure out the logic.

**Comment by keithhackbarth** [comment]
Hi @bellini666,

I hope you're doing well! I wanted to kindly follow up on the review for this PR. We're starting to build features on top of this branch and want to make sure we're heading in the right direction as we already started releasing to production.

I completely understand that maintaining an open-source project is a volunteer effort and labor of love, and I truly appreciate all the work your team puts into it. That said, looking at commit log, I’ve noticed other branches are actively being reviewed and merged, and we’re struggling to get feedback on this one, even though we're financial contributors to the project.

If there’s anything I can do to make the review easier or provide more context, please let me know. Your guidance would be greatly appreciated!

Thank you so much, and I truly value your time and effort!

**Comment by bellini666** [comment]
Hey @keithhackbarth ,

Sorry for taking long to be able to review... I was finally able to settle up in my new house, from now on I should be able to review stuff more fast :)

Thanks for the PR, it looks good! Going to approve and merge it!

In the future, if I take too long, feel free to ping me on Discord :)

**Review by bellini666 — APPROVED** [review]

**Pull request merged**
