### PR TITLE
Fixed pagination being added to non list fields with types that have …

### LINKED ISSUE #252: self referencing Parent relation has pagination if type has it
I have a category type:
```python

@strawberry.django.type(models.Category, pagination=True)
class Category:
    id: auto
    name: auto
    slug: auto
    parent: "Category"
    children: List["Category"]

```

The graphql then adds pagination to the parent relation, which makes no sense, the children it does make sense for.

## Describe the Bug

If the type is a single instance it should not have pagination by default.

## System Information

 - Operating system: Mac
 - Strawberry version (if applicable): 0.176.0

## Additional Context

I can fix it like this:
```python

@strawberry.django.type(models.Category, pagination=True)
class Category:
    id: auto
    name: auto
    slug: auto
    parent: "Category" = strawberry.django.field(pagination=False)
    children: List["Category"]

```

but that shouldn't be needed imho.

Should also note that filters and order are not passed to the parent relation!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/252">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/252/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by hvdklauw**
…pagination.

Also changed the logic in ordering and filtering to match and keep it consistent.

Made it so that ordering, filtering and pagination are not added to the list, but also that the specific function to get the definition returns None.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix #252 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by bellini666 — CHANGES_REQUESTED** [review]
Changes seems fine! Just need to check why the tests are failing

**Comment by bellini666** [comment]
Hey @hvdklauw ,

Just pinging to check if you still want to finish this issue :)
Otherwise I can adjust and merge this for you

**Comment by hvdklauw** [comment]
Hey, I would, but I'm going on vacation for the next 3 weeks.

So feel free to tweak and merge, otherwise I'll pick it up again when I get back

**Comment by bellini666** [comment]
> Hey, I would, but I'm going on vacation for the next 3 weeks.
> 
> So feel free to tweak and merge, otherwise I'll pick it up again when I get back

Np, take your time! :)

**Comment by bellini666** [comment]
Hey @hvdklauw ,

I'm almost sure this was already fixed during the time this has been opened by other fixes, and since this has been sitting here for a while I'm going to close it to clear the backlog, ok?

If that's not the case, let me know so we can reopen this :)

**Comment by hvdklauw** [comment]
Oh sure, np.. I totally forgot about this tbh :D

**Pull request closed without merging**
