### PR TITLE
fix: Extract interface definition in optimizer to fix django-polymorphic

### LINKED ISSUE #550: Broken interfaces with optimiser extension
Querying interfaces crashes when using the optimiser extension caused by #537.

## Describe the Bug
Any field that is an interface will raise an assertion error when queried. `disable_optimizations=True` has no effect. This is caused by the new implementation which uses `schema.schema_converter.from_object` that only supports concrete objects - not interfaces.

## System Information

 - Operating system: any
 - Strawberry version (if applicable): >=0.42.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/550">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/550/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by ManiacMaxo**
## Description

Extracting GraphQL definition from a strawberry definition based on the type (interface or object type)

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fix #550 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

## Summary by Sourcery

This pull request addresses a bug in the optimizer by correctly extracting GraphQL definitions from Strawberry definitions, handling both interface and object types. It also includes a refactoring to improve code clarity and maintainability.

* **Bug Fixes**:
    - Fixed the extraction of GraphQL definitions from Strawberry definitions by correctly handling both interface and object types.
* **Enhancements**:
    - Refactored the optimizer code to use a new helper function `_get_gql_definition` for determining the GraphQL definition based on the type.

### CODE REVIEW

**Comment by patrick91** [comment]
@ManiacMaxo this looks good, could you add a test? 😊

**Comment by ManiacMaxo** [comment]
I'll try to add a unit test

**Review by bellini666 — APPROVED** [review]
Thanks! :)

**Comment by stygmate** [comment]
Seems it don't work if the type class is a relay node.

I've added a test for it here: https://github.com/stygmate/strawberry-graphql-django/blob/test-optimizer-with-polymorphic-relay-node/tests/node_polymorphism/test_optimizer.py

you can test on the test-optimizer-with-polymorphic-relay-node branch of my fork by running: `poetry run pytest tests/node_polymorphism`

If you disable the optimizer in the schema of this test, the test pass.

**Comment by bellini666** [comment]
Thanks for the test @stygmate ,

Will use it to investigate and try to fix the issue :)

**Comment by stygmate** [comment]
@bellini666 I have made a patch. I modified two asserts of instance type.
The second make my test run without fail, i'm unsure of the modification for the first.

Here is the patch: https://github.com/stygmate/strawberry-graphql-django/commit/ccfd204f9e1682d8d57b9cc81160ee4363c52c51

Do you want me to make a pull request ?

**Comment by bellini666** [comment]
Hey @stygmate ,

Oh, I lost your comment, sorry. Yes please, open the PR :)

obs. PRs are always welcomed, no need to wait for my approval 😊

**Pull request merged**
